"""
SMTP credential delivery for the CAP Command Portal.
"""

import os
import smtplib
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
SMTP_FROM = os.environ.get("SMTP_FROM", SMTP_USER)


def send_credentials_email(
    to_email: str,
    mission_no: str,
    username: str,
    password: str,
    enroll_url: str = "",
    qr_code_base64: str = "",
    notes: str = "",
    subject: str = "",
) -> None:
    if not subject:
        subject = f"CAP TAK Credentials — Mission {mission_no}"

    html_qr = ""
    img_attachment = None
    if qr_code_base64:
        html_qr = '<p><img src="cid:qrcode" alt="Enrollment QR" style="max-width:220px"/></p>'
        try:
            img_attachment = base64.b64decode(qr_code_base64)
        except Exception:
            img_attachment = None

    enroll_section = ""
    if enroll_url:
        enroll_section = f'<p><strong>Enrollment URL:</strong> <a href="{enroll_url}">{enroll_url}</a></p>'

    notes_section = f"<p><em>{notes}</em></p>" if notes else ""

    html = f"""
    <html><body style="font-family:sans-serif;color:#1f2937;max-width:520px;margin:0 auto">
      <div style="background:#0d1b3e;padding:16px 24px;border-radius:8px 8px 0 0">
        <span style="background:#FFC72C;color:#0d1b3e;font-weight:800;padding:3px 8px;border-radius:4px;font-size:.8rem">CAP</span>
        <span style="color:#fff;font-size:1rem;margin-left:8px;font-weight:600">Illinois Wing — TAK Command Portal</span>
      </div>
      <div style="border:1px solid #e4e6ef;border-top:none;border-radius:0 0 8px 8px;padding:24px">
        <h2 style="color:#003087;margin-top:0">Mission {mission_no} — TAK Credentials</h2>
        <table style="border-collapse:collapse;width:100%;font-size:.95rem">
          <tr><td style="padding:6px 0;color:#6b7280;width:120px">Username</td>
              <td style="padding:6px 0;font-family:monospace;font-weight:600">{username}</td></tr>
          <tr><td style="padding:6px 0;color:#6b7280">Password</td>
              <td style="padding:6px 0;font-family:monospace;font-weight:600">{password}</td></tr>
        </table>
        {enroll_section}
        {html_qr}
        {notes_section}
        <hr style="border:none;border-top:1px solid #e4e6ef;margin:16px 0"/>
        <p style="font-size:.8rem;color:#6b7280">
          This message was generated by the CAP Illinois Wing TAK Command Portal.
          Do not share your credentials. Contact your mission coordinator with questions.
        </p>
      </div>
    </body></html>
    """

    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"] = SMTP_FROM
    msg["To"] = to_email

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(f"Mission {mission_no} | Username: {username} | Password: {password}", "plain"))
    alt.attach(MIMEText(html, "html"))
    msg.attach(alt)

    if img_attachment:
        img = MIMEImage(img_attachment)
        img.add_header("Content-ID", "<qrcode>")
        img.add_header("Content-Disposition", "inline", filename="qrcode.png")
        msg.attach(img)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.login(SMTP_USER, SMTP_PASS)
        smtp.sendmail(SMTP_FROM, [to_email], msg.as_string())


def send_batch(
    recipients: list[str],
    mission_no: str,
    username: str,
    password: str,
    enroll_url: str = "",
    qr_code_base64: str = "",
    subject: str = "",
    notes: str = "",
) -> list[dict]:
    results = []
    for email in recipients:
        try:
            send_credentials_email(
                to_email=email,
                mission_no=mission_no,
                username=username,
                password=password,
                enroll_url=enroll_url,
                qr_code_base64=qr_code_base64,
                notes=notes,
                subject=subject,
            )
            results.append({"email": email, "success": True})
        except Exception as e:
            results.append({"email": email, "success": False, "error": str(e)})
    return results
